INSERT INTO event () VALUES("Érdekes esemény", "Budapest valami utca 19/4", "Leirás. (descriptio), valamely tárgy vagy tünemény külső megjelenésének szóbeli előadása. Leirhatók térbeli tárgyak vagy időbeli tünemények; egyedi, faji és még általánosabb egységek. A L. természete szerint mindig közlő előadás, ellentétben az értekező előadással, mely a tények lényegének megfejtésével foglalkozik.");
INSERT INTO event VALUES("Érdekes esemény", "Budapest valami utca 19/4", "Leirás. (descriptio), valamely tárgy vagy tünemény külső megjelenésének szóbeli előadása. Leirhatók térbeli tárgyak vagy időbeli tünemények; egyedi, faji és még általánosabb egységek. A L. természete szerint mindig közlő előadás, ellentétben az értekező előadással, mely a tények lényegének megfejtésével foglalkozik.");
INSERT INTO event VALUES("Érdekes esemény", "Budapest valami utca 19/4", "Leirás. (descriptio), valamely tárgy vagy tünemény külső megjelenésének szóbeli előadása. Leirhatók térbeli tárgyak vagy időbeli tünemények; egyedi, faji és még általánosabb egységek. A L. természete szerint mindig közlő előadás, ellentétben az értekező előadással, mely a tények lényegének megfejtésével foglalkozik.");
INSERT INTO event VALUES("Érdekes esemény", "Budapest valami utca 19/4", "Leirás. (descriptio), valamely tárgy vagy tünemény külső megjelenésének szóbeli előadása. Leirhatók térbeli tárgyak vagy időbeli tünemények; egyedi, faji és még általánosabb egységek. A L. természete szerint mindig közlő előadás, ellentétben az értekező előadással, mely a tények lényegének megfejtésével foglalkozik.");
INSERT INTO event VALUES("Érdekes esemény", "Budapest valami utca 19/4", "Leirás. (descriptio), valamely tárgy vagy tünemény külső megjelenésének szóbeli előadása. Leirhatók térbeli tárgyak vagy időbeli tünemények; egyedi, faji és még általánosabb egységek. A L. természete szerint mindig közlő előadás, ellentétben az értekező előadással, mely a tények lényegének megfejtésével foglalkozik.");

INSERT INTO menu VALUES ("Főoldal", "ez a főoldal textez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal text");
INSERT INTO menu VALUES ("Anyagok", "ez a főoldal textez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal text");
INSERT INTO menu VALUES ("Fórum", "ez a főoldal textez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal text");
INSERT INTO menu VALUES ("Kapcsolat", "ez a főoldal textez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal text");
INSERT INTO menu VALUES ("Rólunk", "ez a főoldal textez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal textez a főoldal text \n ez a főoldal textez a főoldal text");